### ISSUE TITLE
Dependency Injection Support?

### ISSUE THREAD

**Issue by drub0y** [christopherread/Obvs#10]
Has any thought been given to DI support in Obvs?

It tends to be very hard to go back and bake in support for DI into frameworks later. Is it worth introducing low level support for dependency resolution now while it's early goings to avoid the pain later? You could either introduce a proprietary `IDependencyResolver` interface as part of Obvs core or have Obvs take a dependency on the [`Microsoft.Framework.DependencyInjection`](https://www.nuget.org/packages/Microsoft.Framework.DependencyInjection) package which would come with the added benefit of everyone implementing direct support for that for all the popular containers (e.g. AutoFac, Ninject, Unity, etc.) since it's a building block of all the new frameworks in .NET vNext. The downside of taking the dependency on that is that it's still beta and that would mean the version of Obvs that takes that dependency would need to be a beta version itself until that dependency RTMd.

**Comment by inter8ection** [comment]
Hi, yes I had given it some thought, as we tend to use a lot of Ninject in the systems I work on. Initially I was binding the Obvs interfaces in Ninject modules, but I found this didn't give me any advantages - in fact it  made it difficult to figure out how Obvs  was configured, because instead of nested composed constructors I had bind statements floating around in various Ninject modules which may or may not be loaded.

So now Obvs is designed to be configured using the fluent config, or just nest constructors by hand, and the IServiceBus interface bound to the resulting class, using whichever DI framework you prefer, which in turn doesn't require any particular support.

My general stance on DI these days is only use it when you need it, as it's often a sign your project has become to big if you can't bootstrap it yourself.

**Comment by drub0y** [comment]
Yeah, I just reached that point where, at least for my tests, I needed a way to supply dependencies to my configuration provider, but I didn't want to sacrifice the use of the fluent interface. I suppose I can provide my own fluent configuration methods to supply overrides for those dependencies to cover this scenario.

The more I thought about it over the weekend, the more I realized that if you really liked working with your favorite container then you could totally just go that route already with Obvs. The only thing you really give up is the "natural" fluent interface of Obvs configuration API itself. So I guess the question is, is it worth it to bake DI directly into Obvs to allow the hybrid of the two or not?

[I did some extremely rapid prototyping here](https://github.com/drub0y/Obvs/commit/872477c803f0fc43c233fcd39fae6ac1a3173b19) on what things might start to look like if Obvs itself had it baked in. I basically ripped the dependency resolver interface/implementation from SignalR as a jumping off point and made some configuration interfaces and whatnot. Again, it's extremely rough, I just wanted to see where things went and what it might feel like.

**Comment by inter8ection** [comment]
My point was users of Obvs should only ever need IServiceBus to be injected, and usually as a singleton. So you use the fluent interface to configure that, and then bind IServiceBus to the resulting ServiceBus using your DI framework of choice, without needing to bake any DI framework into Obvs.

I started with using a DI framework before the fluent interface existed. The fluent interface was as a result of not liking what configuration using DI framework binding looked like.

I'll take a look at your dependency resolver stuff today, just on my phone at the moment :)

**Comment by drub0y** [comment]
Right, yeah, I mean I've given it more thought and I completely understand what you're saying and agree. If someone wants a container then they're going to be used to configuring/connecting all the components using that style already. For people who aren't using a container and want to avoid all the "new" calls they can just use the fluent interface.

Like I said, I can work around my problem by providing a specific overload of my `WithAzureServiceBus` fluent configuration method and allow the dependencies to be overridden there.

**Comment by inter8ection** [comment]
Having said all that, I would like people to be able to use Obvs in the way they are most comfortable, which means providing support for them to use their DI frameworks. So happy to continue with this if you like.

Would the plan also be to provide Extension libraries for popular DI frameworks?

**Comment by drub0y** [comment]
Yeah, that's exactly what I was thinking. There would be implementations of the `IDependencyResolver` for all the popular DI frameworks and then a `UsingDependencyResolver(IDependencyResolver resolver)`  on the core configuration interfaces, but there could be framework specific extension methods to make this even clearer. So, for example let's say there's an `Obvs.DependencyInjection.AutoFac` library/package; in addition to the actual `IDependencyResolver` implementation, it could introduce a `UsingAutofacContainer()` extension method that would basically look something like:

```C#
public ICanCreate UsingAutofacContainer(this IWhateverFluentConfigurationInterfaceMakesSense config, IContainer container)
{
    // NOTE: uses the core framework method, just makes life simple for the person who knows Autofac 
    config.UsingDependencyResolver(new AutofacDependencyResolver(container));
}
```
The real change would be that Obvs's fluent configuration as it exists now would need to fill the container initially with its default types, then stop storing/instantiating any dependencies on its own and instead just push things into the dependency container via `IDependencyResolver::Register`. Then methods like `Create` and `CreateClient` would simply call `IDependencyResolver::Resolve` to resolve a fully baked instances in the end.

So it's obviously not trivial and perhaps something that would be better undertaken as part of a 2.0 project scope.

**Comment by MovGP0** [comment]
it is actually quite easy. just create a factory method that sets up the observable using the fluid interface. then you can inject the factory method. Create additional factory methods for alternative configurations and mocks as needed.

**Comment by megakid** [comment]
I think @MovGP0's final post sums up perfectly the accepted approach to Obvs + DI.  Closing this.
