### ISSUE TITLE
Question: .net Core?

### ISSUE THREAD

**Issue by gusmanb** [christopherread/Obvs#25]
Hi.

Does this library support .net Core? We're starting a new project on .net Core and would like to use this library for IPC.

Cheers.

**Comment by inter8ection** [comment]
Hello, there has been some work done on this in the past, but was put on hold due to none of the major transport client libraries support .Net Core yet. I will find out from @megakid where this got to and reply when I know. Thanks.

**Comment by gusmanb** [comment]
Hello again.

I'm on the process of porting it to .net Core, I already have the code for the library and for the RabbitMQ transport, it needs to be tested. Can youtake a look to see if the naming convention is OK for you so we can merge those when I finish the tests?

They are at:

https://github.com/gusmanb/Obvs
https://github.com/gusmanb/Obvs.RabbitMQ

Cheers.

**Comment by inter8ection** [comment]
Hello, just had a quick look. I have not been following the .NET Standard progress very closely and it's been changing a bit since the initial .NET Core releases. Is the plan to have an Obvs.Standard library, as opposed to converting the main Obvs library to .NET Standard instead?

On another note, the last thing you'll need is at least one Obvs.Serialization library, I think the other extensions like logging and monitoring are optional.

**Comment by gusmanb** [comment]
Well, as you correctly point .net Standard is istill changing, so for now I would keep two separate libraries, I think it would be safer, and when .net Standard gets more stable (let's name it V2.0) then just dropping the support for the classic one would be enough.

I will check this evening the serialization libraries.

Cheers.

**Comment by gusmanb** [comment]
Hi.

I got all the serialization libraries ported to .net standard [here](https://github.com/gusmanb/Obvs.Serialization).

Next week I will create a test environment and start checking everything together, I will post updates here.

Cheers.

**Comment by inter8ection** [comment]
Feel free to pop into the Gitter channel as well so we can chat about it there.

**Comment by megakid** [comment]
Great work @gusmanb - that all looks good.  However, I think we should migrate the existing code to .NET standard in-place as v4.0 release.  People can remain on v3.0 if they don't want to risk the new version but any new features should be done on the .NET core (v4.0) codebase.

**Comment by inter8ection** [comment]
@gusmanb @megakid I agree with that, so create a v4 branch for now and leave v3 on master. Then any new features can be merged across. I can set up Appveyor builds for the v4 branches. Also it should be safe to release onto nuget as v4 if the target is specified correctly.

**Comment by gusmanb** [comment]
Ok, I when I have some spare time this week will get in the gitter channel and coordinate the V4 branch.

**Comment by megakid** [comment]
We're one step closer to this after https://github.com/inter8ection/Obvs/pull/27

**Comment by christopherread** [comment]
This has now been done in https://github.com/christopherread/Obvs/pull/28 so I am closing this issue. Although I still need to test it some more and deploy to nuget.
