### ISSUE TITLE
[Question] In-memory bus usage example

### ISSUE THREAD

**Issue by idubnori** [christopherread/Obvs#31]
> Don't distribute if you don't need to, Obvs ServiceBus includes a local in-memory bus.

Is there any usage examples or unit test for in-memory bus?
I could not find out somethings like  `.WithInMemoryEndpoints<T>()`.

**Comment by christopherread** [comment]
The best place to look currently would be https://github.com/inter8ection/Obvs/blob/master/Obvs.Tests/TestServiceBus.cs where you can find two tests on the local bus called
ShouldPublishMessagesToLocalBusWhenConfigured()
ShouldPublishMessagesWithNoEndpointToLocalBusWhenConfigured()

The basic idea with the local bus is that the Obvs service bus can tell, by how you have configured your endpoints to your services, if you will receive the messages back over the transport and therefore avoids the de-duplicating problem. So it has two configuration options:

.PublishLocally().AnyMessagesWithNoEndpointClients()

which will only publish messages locally which you are guaranteed not to receive over the wire/transport as Obvs can tell that you aren't subscribed to them as they are messages for server endpoints, or

.PublishLocally().OnlyMessagesWithNoEndpoints()

which will only publish messages which have no service endpoints configured, ie: they are internal messages which never go over the wire.

**Comment by idubnori** [comment]
Thank you for your detailed explanation.

In any case, should set any endpoints, if use in-memory bus?
Is there any endpoint implementations like `NoneEndpoint`?

**Comment by christopherread** [comment]
Hello, the intended usage is for Obvs is to have at least one endpoint that's 'over the wire', where the localbus is just an optimisation if you happen to host one or more endpoints in the same process.

Saying that, it can be done by creating a fake/default endpoint that does nothing, like so:

public class MyEndpoint : ServiceEndpoint
    {
        public MyEndpoint() 
            : base(
                  new DefaultMessageSource<IRequest>(),
                  new DefaultMessageSource<ICommand>(), 
                  new DefaultMessagePublisher<IEvent>(), 
                  new DefaultMessagePublisher<IResponse>(), 
                  typeof(MyEndpoint))         
        {
        }
    }
var a = ServiceBus
                .Configure()
                .WithEndpoint(new MyEndpoint())
                .PublishLocally().OnlyMessagesWithNoEndpoints()
                .CreateServiceBus();

**Comment by christopherread** [comment]
Please join our Gitter chat https://gitter.im/christopherread/Obvs if you want to discuss it further. Closing this issue now.
